name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v-no
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy vno.d.ts
        run: |
          mkdir -p v-no-script/src/utils/ && cp src/vno.d.ts v-no-script/src/utils/
          mkdir -p v-no-doc-script/src/utils/ && cp src/vno.d.ts v-no-doc-script/src/utils/
          mkdir -p v-no-script-template/src/ && cp src/vno.d.ts v-no-script-template/src/

      - name: Update vno.d.ts (v-no-script)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_CONFIG_NAME: AkrISrn
          REPOSITORY_NAME: akrisrn/v-no-script
          BRANCH: master
          FOLDER: v-no-script
          COMMIT_MESSAGE: update vno.d.ts
          CLEAN: false

      - name: Update vno.d.ts (v-no-doc-script)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_CONFIG_NAME: AkrISrn
          REPOSITORY_NAME: akrisrn/v-no-doc-script
          BRANCH: master
          FOLDER: v-no-doc-script
          COMMIT_MESSAGE: update vno.d.ts
          CLEAN: false

      - name: Update vno.d.ts (v-no-script-template)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_CONFIG_NAME: AkrISrn
          REPOSITORY_NAME: akrisrn/v-no-script-template
          BRANCH: master
          FOLDER: v-no-script-template
          COMMIT_MESSAGE: update vno.d.ts
          CLEAN: false

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build
        run: yarn && yarn run build

      - name: Deploy v-no-template
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_CONFIG_NAME: AkrISrn
          REPOSITORY_NAME: akrisrn/v-no-template
          BRANCH: master
          FOLDER: dist
          COMMIT_MESSAGE: release v${{ env.RELEASE_VERSION }}

      - name: Build (hash)
        run: cp .env.hash .env.local && yarn run build

      - name: Deploy v-no-hash-template
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_CONFIG_NAME: AkrISrn
          REPOSITORY_NAME: akrisrn/v-no-hash-template
          BRANCH: master
          FOLDER: dist
          COMMIT_MESSAGE: release v${{ env.RELEASE_VERSION }}

      - name: Checkout v-no-doc
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: akrisrn/v-no-doc
          path: v-no-doc

      - name: Build (doc)
        run: |
          cp .env.doc .env.local
          echo "" >> src/ts/async/prismjs.ts
          yarn run build-modern+clean
          rm -r v-no-doc/assets/css/ v-no-doc/assets/js/
          cp -r dist/* v-no-doc/

      - name: Deploy v-no-doc
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_CONFIG_NAME: AkrISrn
          REPOSITORY_NAME: akrisrn/v-no-doc
          BRANCH: master
          FOLDER: v-no-doc
          COMMIT_MESSAGE: release v${{ env.RELEASE_VERSION }}
